{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ima
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/klprint/r-ima
  git_tag: v0.0.0.9000

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-matrix

  run:
    - r-base
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('IMA')"           # [not win]
    - "\"%R%\" -e \"library('IMA')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/klprint/r-ima
  license: MIT
  summary: Approximates a matrix factorization for integer matrices.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: IMA
# Title: Integer Matrix Approximation
# Version: 0.0.0.9000
# Authors@R: person("Samuel", "Church", , "samuelhchurch@gmail.com", role = c("aut", "cre"))
# Description: Approximates a matrix factorization for integer matrices.
# License: MIT + file LICENSE
# Encoding: UTF-8
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.2
# Imports: Matrix

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
